print("How many miles were driven?") 
x = int(input(">"))
print("How many gallons of gas were used?")
y = int(input(">"))
forumla = int(x/y)
print(str('Your car gets' + formula + 'miles per gallon'))
